# Site settings
title: Dr. Ayon Borthakur
email: ayon.borthakur@ai.iith.ac.in
description: Academic webpage of Dr. Ayon Borthakur
baseurl: ""
url: ""

#theme: minima


# Google analytics ID: Remove or use your own!
# google_analytics: UA-167467135-1
# google_analytics_4: G-02KDGRRB2T
# google_tag_manager: GTM-TZ9Z7HZ

# Footer info
affiliation: >
    Dr. Ayon Borthakur<br/>
    Assistant Professor<br/>
    <a href="https://ai.iith.ac.in/" target="_blank">Dept. of Artificial Intelligence</a><br/>
    IIT Hyderabad

location: >
  112C, Academic Block C <br/>
  IIT Hyderabad <br/>
  Near NH-65, Kandi, Sangareddy <br/>
  Telangana 502285, India

contact: >
    <a href="mailto:ayon.borthakur@ai.iith.ac.in" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Ayon via email</a> <br/>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: patents & publications
  - name: talks & posters
#  - name: research
  - name: software
  - name: openings
  - name: teaching

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: ['jekyll/scholar']

scholar:

  last_name: Borthakur
  first_name: [Ayon]

  style: shb
  locale: en

  source: /cv/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
